CREATE TABLE [dbo].[IMAGE_LIBRARY](
	[IMAGE_LIBRARY_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](40) NULL,
	[IMAGE_DATA] [varbinary](max) NULL,
	[IMAGE_CONTENT_TYPE] [varchar](100) NULL,
	[IMAGE_SIZE] [int] NULL,
	[IMAGE_MODIFIED_DATETIME] [datetime] NULL,
	[FOLDER_PATH] [varchar](100) NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_NAME] [varchar](50) NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_NAME] [varchar](50) NULL,
	[STATUS] [varchar](1) NULL,
 CONSTRAINT [PK_IMAGE_LIBRARY] PRIMARY KEY CLUSTERED 
(
	[IMAGE_LIBRARY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
